import { inviteUser } from "@/app/actions/users";
import { AdminPageHeader } from "@/components/admin-page";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { createClient } from "@/lib/supabase/server";

export default async function InviteUserPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) { const query = await searchParams; const supabase = await createClient(); const { data: dependencies } = supabase ? await supabase.from("dependencies").select("id,name").eq("is_active", true).is("archived_at", null).order("name") : { data: null }; return <><AdminPageHeader title="Crear usuario interno" description="Solo OWNER / Attorney General puede crear cuentas. Supabase Auth crea usuarios confirmados sin enviar correos." />{query.error && <p className="mb-5 rounded border border-red-200 bg-red-50 p-4 text-sm text-red-800">{query.error}</p>}<Card className="max-w-3xl"><CardContent><form action={inviteUser} className="grid gap-5 md:grid-cols-2"><Field label="Nombre completo" name="full_name" /><Field label="Correo de autenticación" name="email" type="email" /><Field label="Correo visible institucional" name="institutional_email" type="email" required={false} /><Field label="Contraseña temporal" name="temporary_password" type="password" /><SelectField label="Rol" name="role" values={["OWNER","ATTORNEY_GENERAL","DEPUTY_ATTORNEY_GENERAL","DOJ_ATTORNEY","CASE_AGENT","EVIDENCE_CUSTODIAN","CLERK","JUDGE","GRAND_JUROR","TRIAL_JUROR","FOREPERSON","JUEZ","FISCAL","ABOGADO","INVESTIGADOR","ADMINISTRADOR","PERSONAL_AUTORIZADO","ADMIN_INSTITUCIONAL","SUPER_ADMIN","MAGISTRADO_CORTE_SUPREMA","MAGISTRADO_TRIBUNAL","JUEZ_CIRCUITO","JUEZ_MUNICIPAL","SECRETARIO_GENERAL","SECRETARIO_DESPACHO","OFICIAL_MAYOR","AUXILIAR","RADICADOR","REPARTO","ARCHIVO","GOBERNACION_COMUNICACIONES","CONSULTA_PUBLICA"]} /><div className="space-y-2"><Label htmlFor="dependency_id">Dependencia</Label><select id="dependency_id" name="dependency_id" className="h-9 w-full rounded-md border px-3 text-sm"><option value="">Sin asignar</option>{(dependencies ?? []).map((dependency) => <option key={dependency.id} value={dependency.id}>{dependency.name}</option>)}</select></div><Field label="Cargo visible" name="position_title" required={false} /><p className="rounded border border-blue-100 bg-blue-50 p-3 text-xs leading-5 text-blue-900 md:col-span-2">El usuario queda activo y podrá iniciar sesión inmediatamente con la contraseña temporal. Los jurados deben usar GRAND_JUROR o TRIAL_JUROR y solo verán sus proceedings asignados. Deberá cambiarla en el primer acceso. Los correos <code>.test</code> son válidos para autenticación interna y no requieren buzón real.</p><div className="flex items-end justify-end md:col-span-2"><Button type="submit" className="bg-[#153b5c]">Crear usuario activo</Button></div></form></CardContent></Card></>; }
function Field({ label, name, type = "text", required = true }: { label: string; name: string; type?: string; required?: boolean }) { return <div className="space-y-2"><Label htmlFor={name}>{label}</Label><Input id={name} name={name} type={type} required={required} /></div>; }
function SelectField({ label, name, values }: { label: string; name: string; values: string[] }) { return <div className="space-y-2"><Label htmlFor={name}>{label}</Label><select id={name} name={name} required className="h-9 w-full rounded-md border px-3 text-sm">{values.map((value) => <option key={value}>{value}</option>)}</select></div>; }
