import { inviteUser } from "@/app/actions/users";
import { AdminPageHeader } from "@/components/admin-page";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { dependencies } from "@/lib/demo-data";

export default async function InviteUserPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) { const query = await searchParams; return <><AdminPageHeader title="Invitar usuario interno" description="Supabase Auth enviará un enlace seguro para que la persona establezca su contraseña." />{query.error && <p className="mb-5 rounded border border-red-200 bg-red-50 p-4 text-sm text-red-800">{query.error}</p>}<Card className="max-w-3xl"><CardContent><form action={inviteUser} className="grid gap-5 md:grid-cols-2"><Field label="Nombre completo" name="full_name" /><Field label="Correo institucional" name="email" type="email" /><SelectField label="Rol" name="role" values={["PRESIDENCIA_TRIBUNAL","MAGISTRADO","JUEZ_CIRCUITO","SECRETARIA","RELATORIA","GOBERNACION","CONSULTA"]} /><div className="space-y-2"><Label htmlFor="dependency_id">Dependencia</Label><select id="dependency_id" name="dependency_id" className="h-9 w-full rounded-md border px-3 text-sm"><option value="">Sin asignar</option>{dependencies.map((dependency, index) => <option key={dependency} value={`10000000-0000-0000-0000-${String(index + 1).padStart(12, "0")}`}>{dependency}</option>)}</select></div><Field label="Cargo" name="position_title" required={false} /><div className="flex items-end justify-end"><Button type="submit" className="bg-[#153b5c]">Enviar invitación</Button></div></form></CardContent></Card></>; }
function Field({ label, name, type = "text", required = true }: { label: string; name: string; type?: string; required?: boolean }) { return <div className="space-y-2"><Label htmlFor={name}>{label}</Label><Input id={name} name={name} type={type} required={required} /></div>; }
function SelectField({ label, name, values }: { label: string; name: string; values: string[] }) { return <div className="space-y-2"><Label htmlFor={name}>{label}</Label><select id={name} name={name} required className="h-9 w-full rounded-md border px-3 text-sm">{values.map((value) => <option key={value}>{value}</option>)}</select></div>; }
