import { ROLEPLAY_NOTICE } from "@/lib/identity";

type PdfPage = string[];

const PAGE_WIDTH = 612;
const PAGE_HEIGHT = 792;
const MARGIN = 54;
const LINE_HEIGHT = 13;
const BODY_SIZE = 10.5;

export type DocketPdfSection = {
  title: string;
  rows: string[];
};

export function buildDojRecordPdf(input: {
  title: string;
  subtitle: string;
  classification: string;
  generatedBy: string;
  sections: DocketPdfSection[];
}) {
  const pages: PdfPage[] = [[]];
  let page = pages[0];
  let y = PAGE_HEIGHT - MARGIN;

  const nextPage = () => {
    addFooter(page, pages.length, input.classification);
    page = [];
    pages.push(page);
    y = PAGE_HEIGHT - MARGIN;
    addHeader(page, input);
    y -= 72;
  };
  const ensure = (height: number) => {
    if (y - height < MARGIN + 40) nextPage();
  };
  const text = (value: string, x: number, size = BODY_SIZE, font = "F1") => {
    page.push(`BT /${font} ${size} Tf ${x} ${y} Td ${pdfString(value)} Tj ET`);
  };
  const line = (x1: number, y1: number, x2: number, y2: number, width = 0.7) => {
    page.push(`${width} w ${x1} ${y1} m ${x2} ${y2} l S`);
  };
  const paragraph = (value: string, x = MARGIN, width = PAGE_WIDTH - MARGIN * 2, size = BODY_SIZE) => {
    const rows = wrap(value || "No information recorded.", Math.floor(width / (size * 0.48)));
    ensure(rows.length * LINE_HEIGHT + 5);
    for (const row of rows) {
      text(row, x, size);
      y -= LINE_HEIGHT;
    }
  };
  const heading = (value: string) => {
    ensure(28);
    y -= 8;
    text(value.toUpperCase(), MARGIN, 12, "F2");
    line(MARGIN, y - 5, PAGE_WIDTH - MARGIN, y - 5);
    y -= 20;
  };

  addHeader(page, input);
  y -= 72;
  heading("Table of contents");
  input.sections.forEach((section, index) => paragraph(`${index + 1}. ${section.title}`, MARGIN + 8));
  for (const section of input.sections) {
    heading(section.title);
    if (section.rows.length === 0) paragraph("No records in this section.");
    for (const row of section.rows) paragraph(row);
  }
  heading("Generation");
  paragraph(`Generated at: ${new Date().toISOString()}`);
  paragraph(`Generated by: ${input.generatedBy}`);
  paragraph(ROLEPLAY_NOTICE);
  addFooter(page, pages.length, input.classification);
  return assemblePdf(pages);
}

function addHeader(page: PdfPage, input: { title: string; subtitle: string; classification: string }) {
  page.push(`1.3 w ${MARGIN} ${PAGE_HEIGHT - MARGIN - 8} m ${PAGE_WIDTH - MARGIN} ${PAGE_HEIGHT - MARGIN - 8} l S`);
  page.push(`BT /F2 13 Tf ${MARGIN} ${PAGE_HEIGHT - MARGIN + 8} Td ${pdfString("U.S. Department of Justice Roleplay Portal")} Tj ET`);
  page.push(`BT /F2 11 Tf ${MARGIN} ${PAGE_HEIGHT - MARGIN - 18} Td ${pdfString(input.title)} Tj ET`);
  page.push(`BT /F1 9 Tf ${MARGIN} ${PAGE_HEIGHT - MARGIN - 33} Td ${pdfString(input.subtitle)} Tj ET`);
  page.push(`BT /F2 8 Tf ${PAGE_WIDTH - 190} ${PAGE_HEIGHT - MARGIN - 18} Td ${pdfString(input.classification)} Tj ET`);
}

function addFooter(page: PdfPage, pageNumber: number, classification: string) {
  page.push(`0.7 w ${MARGIN} 38 m ${PAGE_WIDTH - MARGIN} 38 l S`);
  page.push(`BT /F2 7.5 Tf ${MARGIN} 25 Td ${pdfString(`ROLEPLAY DOCUMENT - ${classification}`)} Tj ET`);
  page.push(`BT /F1 8 Tf ${PAGE_WIDTH - 180} 25 Td ${pdfString(`Page ${pageNumber} - Developed by: kcobainn`)} Tj ET`);
}

function assemblePdf(pages: PdfPage[]) {
  const objects: string[] = [];
  objects.push("<< /Type /Catalog /Pages 2 0 R >>");
  objects.push(`<< /Type /Pages /Kids [${pages.map((_, index) => `${3 + index * 2} 0 R`).join(" ")}] /Count ${pages.length} >>`);
  pages.forEach((content, index) => {
    const pageObj = 3 + index * 2;
    const contentObj = pageObj + 1;
    objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_WIDTH} ${PAGE_HEIGHT}] /Resources << /Font << /F1 << /Type /Font /Subtype /Type1 /BaseFont /Times-Roman /Encoding /WinAnsiEncoding >> /F2 << /Type /Font /Subtype /Type1 /BaseFont /Times-Bold /Encoding /WinAnsiEncoding >> /F3 << /Type /Font /Subtype /Type1 /BaseFont /Times-Italic /Encoding /WinAnsiEncoding >> >> >> /Contents ${contentObj} 0 R >>`);
    const stream = content.join("\n");
    objects.push(`<< /Length ${Buffer.byteLength(stream, "utf8")} >>\nstream\n${stream}\nendstream`);
  });
  let pdf = "%PDF-1.4\n";
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets.push(Buffer.byteLength(pdf, "utf8"));
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });
  const xref = Buffer.byteLength(pdf, "utf8");
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  offsets.slice(1).forEach((offset) => { pdf += `${String(offset).padStart(10, "0")} 00000 n \n`; });
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
  return Buffer.from(pdf, "utf8");
}

function wrap(value: string, max: number) {
  const words = value.replace(/\s+/g, " ").trim().split(" ");
  const lines: string[] = [];
  let current = "";
  for (const word of words) {
    const next = current ? `${current} ${word}` : word;
    if (next.length > max && current) {
      lines.push(current);
      current = word;
    } else {
      current = next;
    }
  }
  if (current) lines.push(current);
  return lines.length ? lines : [""];
}

function pdfString(value: string) {
  let output = "(";
  for (const char of value) {
    const code = winAnsiCode(char);
    if (code === 0x28 || code === 0x29 || code === 0x5c) output += `\\${String.fromCharCode(code)}`;
    else if (code >= 0x20 && code <= 0x7e) output += String.fromCharCode(code);
    else output += `\\${code.toString(8).padStart(3, "0")}`;
  }
  return `${output})`;
}

function winAnsiCode(char: string) {
  const code = char.charCodeAt(0);
  if (code <= 0x7f || (code >= 0xa0 && code <= 0xff)) return code;
  const mapped: Record<string, number> = {
    "€": 0x80, "‚": 0x82, "ƒ": 0x83, "„": 0x84, "…": 0x85, "†": 0x86, "‡": 0x87,
    "ˆ": 0x88, "‰": 0x89, "Š": 0x8a, "‹": 0x8b, "Œ": 0x8c, "Ž": 0x8e,
    "‘": 0x91, "’": 0x92, "“": 0x93, "”": 0x94, "•": 0x95, "–": 0x96, "—": 0x97,
    "˜": 0x98, "™": 0x99, "š": 0x9a, "›": 0x9b, "œ": 0x9c, "ž": 0x9e, "Ÿ": 0x9f,
  };
  return mapped[char] ?? 0x3f;
}
