export const VALLE_DEL_CAUCA_DEPARTMENT = "Valle del Cauca";

export const VALLE_ELECTION_CITIES = [
  "Cali",
  "Palmira",
  "Buenaventura",
  "Tuluá",
] as const;

export const VALLE_DEL_CAUCA_MUNICIPALITIES = [
  "Cali",
  "Palmira",
  "Buenaventura",
  "Tuluá",
  "Cartago",
  "Buga",
  "Jamundí",
  "Yumbo",
  "Guadalajara de Buga",
  "Candelaria",
  "Florida",
  "Pradera",
  "Zarzal",
  "Sevilla",
  "Caicedonia",
  "Roldanillo",
  "La Unión",
  "La Victoria",
  "Andalucía",
  "El Cerrito",
  "Ginebra",
  "Guacarí",
  "Dagua",
  "Vijes",
  "Restrepo",
  "Riofrío",
  "Trujillo",
  "Bolívar",
  "Versalles",
  "El Dovio",
  "Toro",
  "Ansermanuevo",
  "Argelia",
  "El Águila",
  "Ulloa",
  "Alcalá",
  "Obando",
  "San Pedro",
  "Yotoco",
  "La Cumbre",
  "Calima",
  "Darién",
] as const;

export type ValleMunicipality = (typeof VALLE_DEL_CAUCA_MUNICIPALITIES)[number];
