import type { AppRole } from "@/lib/user-management";

export const PERMISSION_ACTIONS = [
  "view",
  "create",
  "edit",
  "upload",
  "preview",
  "download",
  "archive",
  "restore",
  "hard_delete",
  "publish",
  "finalize",
  "reopen",
  "sign",
  "print",
  "share",
  "repartition",
  "assign_ponente",
  "reschedule",
  "cancel",
  "deactivate",
  "reactivate",
  "assign_role",
  "request",
  "revoke",
  "manage",
  "take_control",
  "send",
  "register_session",
  "register_vote",
  "approve",
  "return",
  "create_in_institution",
  "create_in_dependency",
  "assign_dependency",
  "view_all",
  "view_dependency",
  "assign_leader",
  "edit_public",
  "publish_profile",
  "edit_institution",
  "edit_dependency",
  "edit_title",
  "edit_own",
  "export",
  "mark_completed",
  "create_minutes",
  "view_institution",
  "view_applications",
  "edit_applications",
  "evaluate_applications",
  "close",
  "update_application_status",
  "edit_public_message",
  "ver",
  "crear",
  "editar",
  "configurar_tarjeta",
  "abrir",
  "suspender",
  "reabrir",
  "cerrar",
  "cerrar_definitivo",
  "votar",
  "ver_votos",
  "validar_votos",
  "anular_votos",
  "gestionar_escrutinio",
  "agregar_votos_manuales",
  "validar_votos_manuales",
  "publicar_preliminares",
  "publicar_resultados",
  "declarar_ganador",
  "ver_auditoria",
] as const;

export type PermissionAction = (typeof PERMISSION_ACTIONS)[number];

export const PERMISSION_CATALOG = [
  { resource: "expedientes", label: "Expedientes", actions: ["view", "create", "edit", "archive", "restore", "hard_delete", "share", "repartition", "assign_ponente"] },
  { resource: "providencias", label: "Providencias", actions: ["view", "create", "edit", "publish", "archive", "restore", "hard_delete", "sign", "share", "print"] },
  { resource: "actuaciones", label: "Actuaciones", actions: ["view", "create", "edit", "archive", "restore", "hard_delete"] },
  { resource: "audiencias", label: "Audiencias", actions: ["view", "create", "edit", "reschedule", "cancel", "mark_completed", "create_minutes", "view_all", "view_institution", "view_dependency", "archive", "restore", "hard_delete"] },
  { resource: "actas", label: "Actas", actions: ["view", "create", "edit", "finalize", "reopen", "sign", "print", "archive"] },
  { resource: "documentos", label: "Documentos / pruebas", actions: ["view", "upload", "preview", "download", "archive", "restore", "hard_delete", "share"] },
  { resource: "comunicados", label: "Comunicados", actions: ["view", "create", "edit", "publish", "archive", "restore", "hard_delete"] },
  { resource: "estados", label: "Estados judiciales", actions: ["view", "create", "edit", "publish", "archive", "restore", "hard_delete"], visible: false },
  { resource: "usuarios", label: "Usuarios", actions: ["view", "view_dependency", "view_all", "create", "create_in_dependency", "create_in_institution", "edit", "deactivate", "reactivate", "assign_role", "assign_dependency"] },
  { resource: "roles", label: "Roles y permisos", actions: ["view", "manage"] },
  { resource: "firmas", label: "Firmas", actions: ["view", "request", "sign", "revoke"] },
  { resource: "enlaces", label: "Enlaces compartidos", actions: ["create", "view", "revoke"] },
  { resource: "auditoria", label: "Auditoría", actions: ["view", "export"] },
  { resource: "instituciones", label: "Instituciones", actions: ["view", "manage"] },
  { resource: "dependencias", label: "Dependencias y despachos", actions: ["view", "create", "edit", "manage", "assign_leader"] },
  { resource: "configuracion", label: "Configuración", actions: ["view"] },
  { resource: "edicion", label: "Edición colaborativa", actions: ["take_control"] },
  { resource: "votos", label: "Votos particulares", actions: ["view", "create", "edit", "sign", "publish", "archive", "print"] },
  { resource: "sala", label: "Modo Sala", actions: ["view", "send", "register_session", "register_vote", "approve", "return", "publish"] },
  { resource: "notificaciones", label: "Notificaciones internas", actions: ["view", "manage"] },
  { resource: "perfil", label: "Perfil propio", actions: ["edit", "edit_public", "publish_profile", "edit_institution", "edit_dependency", "edit_title"] },
  { resource: "seleccion", label: "Procesos de selección", actions: ["view", "create", "edit", "publish", "close", "cancel", "view_applications", "edit_applications", "evaluate_applications", "update_application_status", "edit_public_message", "view_all", "view_institution", "view_dependency"] },
  { resource: "elecciones", label: "Elecciones institucionales", actions: ["ver", "crear", "editar", "configurar_tarjeta", "abrir", "suspender", "reabrir", "cerrar", "cerrar_definitivo", "votar", "ver_votos", "validar_votos", "anular_votos", "gestionar_escrutinio", "agregar_votos_manuales", "validar_votos_manuales", "publicar_preliminares", "publicar_resultados", "declarar_ganador", "ver_auditoria"] },
] as const satisfies readonly {
  resource: string;
  label: string;
  actions: readonly PermissionAction[];
  visible?: boolean;
}[];

export const MANAGEABLE_PERMISSION_CATALOG = PERMISSION_CATALOG.filter(
  (item) => !("visible" in item) || item.visible !== false,
);

export const PERMISSION_GROUP_DESCRIPTIONS: Record<PermissionResource,string> = {
  expedientes:"Radicación, consulta, reparto y ciclo de vida de expedientes.",
  providencias:"Redacción, publicación, firma e impresión de decisiones.",
  actuaciones:"Registro y mantenimiento de actuaciones procesales.",
  audiencias:"Programación, edición y control de audiencias.",
  actas:"Elaboración, cierre, firma e impresión de actas.",
  documentos:"Carga, consulta, descarga y custodia de archivos.",
  comunicados:"Creación y publicación de comunicaciones institucionales.",
  estados:"Gestión técnica de estados judiciales.",
  usuarios:"Directorio, creación y administración de usuarios dentro del alcance asignado.",
  roles:"Administración de reglas generales y permisos personalizados.",
  firmas:"Solicitud, aplicación y revocación de firmas documentales.",
  enlaces:"Creación y revocación de accesos compartidos temporales.",
  auditoria:"Consulta y exportación de trazabilidad institucional.",
  instituciones:"Consulta y administración de instituciones raíz.",
  dependencias:"Creación, edición y liderazgo de salas, despachos y juzgados.",
  configuracion:"Ajustes globales del sistema.",
  edicion:"Control de edición colaborativa y recuperación de bloqueos.",
  votos:"Creación, firma y publicación de votos particulares.",
  sala:"Sesiones, votaciones y aprobación en Modo Sala.",
  notificaciones:"Consulta propia y envío institucional autorizado.",
  perfil:"Identidad privada/pública, cargo y asignación del perfil propio.",
  seleccion:"Convocatorias y postulaciones aisladas por institución y despacho.",
  elecciones:"Configuración, votación, escrutinio, validación y publicación de resultados electorales.",
};

export type PermissionResource = (typeof PERMISSION_CATALOG)[number]["resource"];
export type PermissionKey = `${PermissionResource}:${PermissionAction}`;

export const ACTION_LABELS: Record<PermissionAction, string> = {
  view: "Ver",
  create: "Crear",
  edit: "Editar",
  upload: "Subir archivos",
  preview: "Previsualizar",
  download: "Descargar",
  archive: "Archivar",
  restore: "Restaurar",
  hard_delete: "Eliminar definitivo",
  publish: "Publicar",
  finalize: "Finalizar",
  reopen: "Reabrir",
  sign: "Firmar",
  print: "Imprimir / exportar",
  share: "Compartir",
  repartition: "Cambiar dependencia / reparto",
  assign_ponente: "Asignar ponente",
  reschedule: "Reprogramar",
  cancel: "Cancelar",
  deactivate: "Desactivar",
  reactivate: "Reactivar",
  assign_role: "Asignar rol",
  request: "Solicitar",
  revoke: "Revocar",
  manage: "Administrar",
  take_control: "Tomar control de edición",
  send: "Enviar a Sala",
  register_session: "Registrar sesión",
  register_vote: "Registrar votación",
  approve: "Aprobar",
  return: "Devolver a ponente",
  create_in_institution: "Crear en su institución",
  create_in_dependency: "Crear en su dependencia",
  assign_dependency: "Asignar dependencia",
  view_all: "Ver todos los usuarios",
  view_dependency: "Ver usuarios de mi dependencia/despacho",
  assign_leader: "Asignar juez, magistrado/a o responsable",
  edit_public: "Editar identidad pública",
  publish_profile: "Publicar perfil institucional",
  edit_institution: "Cambiar institución propia",
  edit_dependency: "Cambiar dependencia propia",
  edit_title: "Editar cargo propio",
  edit_own: "Editar perfil propio",
  export: "Exportar",
  mark_completed: "Marcar como realizada",
  create_minutes: "Crear acta",
  view_institution: "Ver toda mi institución",
  view_applications: "Ver postulaciones",
  edit_applications: "Gestionar postulaciones",
  evaluate_applications: "Evaluar postulaciones",
  close: "Cerrar proceso",
  update_application_status: "Actualizar estado de postulación",
  edit_public_message: "Editar mensaje público al postulante",
  ver: "Ver",
  crear: "Crear",
  editar: "Editar",
  configurar_tarjeta: "Configurar tarjeta electoral",
  abrir: "Abrir votación",
  suspender: "Suspender votación",
  reabrir: "Reabrir votación",
  cerrar: "Cerrar votación",
  cerrar_definitivo: "Cerrar definitivamente",
  votar: "Votar",
  ver_votos: "Ver votos",
  validar_votos: "Validar votos",
  anular_votos: "Anular votos",
  gestionar_escrutinio: "Gestionar escrutinio",
  agregar_votos_manuales: "Agregar votos manuales",
  validar_votos_manuales: "Validar votos manuales",
  publicar_preliminares: "Publicar preliminares",
  publicar_resultados: "Publicar resultados",
  declarar_ganador: "Declarar ganador",
  ver_auditoria: "Ver auditoría electoral",
};

export const USER_PERMISSION_DESCRIPTIONS: Partial<Record<PermissionAction, string>> = {
  view: "Permite abrir el módulo de usuarios, según el alcance permitido.",
  view_dependency: "Permite ver usuarios asignados a la misma dependencia, despacho, juzgado, sala u oficina.",
  view_all: "Permite ver usuarios de todas las instituciones y dependencias autorizadas.",
  create: "Permite crear usuarios; el destino depende del alcance institucional o de dependencia.",
  create_in_dependency: "Permite crear personal únicamente en la dependencia o despacho asignado al usuario.",
  create_in_institution: "Permite crear usuarios dentro de la misma institución o corporación.",
  assign_dependency: "Permite asignar o cambiar el despacho dentro del alcance autorizado.",
  assign_role: "Permite asignar roles autorizados; nunca permite crear OWNER ni evadir cuentas protegidas.",
  edit: "Permite modificar usuarios que estén dentro del alcance autorizado.",
  edit_own: "Permite actualizar los datos seguros del perfil propio sin modificar rol, correo ni protecciones.",
  deactivate: "Permite desactivar usuarios dentro del alcance, salvo cuentas protegidas.",
  reactivate: "Permite reactivar usuarios dentro del alcance autorizado.",
};

const allPermissionKeys = PERMISSION_CATALOG.flatMap(({ resource, actions }) =>
  actions.map((action) => `${resource}:${action}` as PermissionKey),
);

const judicialView = [
  "expedientes:view", "providencias:view", "actuaciones:view", "audiencias:view",
  "actas:view", "documentos:view", "documentos:preview", "documentos:download",
  "firmas:view", "enlaces:view",
] as PermissionKey[];
const adjudicatorWrite = [
  "providencias:create", "providencias:edit", "providencias:publish", "providencias:sign", "providencias:share", "providencias:print",
  "actuaciones:create", "audiencias:create", "audiencias:edit", "audiencias:reschedule", "audiencias:cancel",
  "actas:create", "actas:edit", "actas:finalize", "actas:reopen", "actas:sign", "actas:print",
  "documentos:upload", "documentos:share", "enlaces:create", "firmas:sign", "firmas:request", "firmas:revoke",
] as PermissionKey[];
const selfService = ["perfil:edit","perfil:edit_public"] as PermissionKey[];
const selectionManage = ["seleccion:view","seleccion:create","seleccion:edit","seleccion:publish","seleccion:close","seleccion:cancel","seleccion:view_applications","seleccion:edit_applications","seleccion:evaluate_applications","seleccion:update_application_status","seleccion:edit_public_message","seleccion:view_dependency"] as PermissionKey[];
const electionManage = ["elecciones:ver","elecciones:crear","elecciones:editar","elecciones:configurar_tarjeta","elecciones:abrir","elecciones:suspender","elecciones:reabrir","elecciones:cerrar","elecciones:cerrar_definitivo","elecciones:votar","elecciones:ver_votos","elecciones:validar_votos","elecciones:anular_votos","elecciones:gestionar_escrutinio","elecciones:agregar_votos_manuales","elecciones:validar_votos_manuales","elecciones:publicar_preliminares","elecciones:publicar_resultados","elecciones:declarar_ganador","elecciones:ver_auditoria"] as PermissionKey[];

export const DEFAULT_ROLE_PERMISSION_KEYS: Record<AppRole, readonly PermissionKey[]> = {
  SUPER_ADMIN: allPermissionKeys,
  ADMIN_INSTITUCIONAL: [...judicialView, ...selfService, ...selectionManage.filter((key)=>key!=="seleccion:view_dependency"), ...electionManage.filter((key)=>!["elecciones:declarar_ganador"].includes(key)), "audiencias:view_institution", "seleccion:view_institution", "perfil:publish_profile", "perfil:edit_title", "expedientes:edit", "expedientes:repartition", "expedientes:assign_ponente", "documentos:upload", "enlaces:create", "usuarios:view", "usuarios:view_dependency", "usuarios:create", "usuarios:create_in_institution", "usuarios:create_in_dependency", "usuarios:edit", "usuarios:deactivate", "usuarios:reactivate", "usuarios:assign_role", "usuarios:assign_dependency", "instituciones:view", "dependencias:view", "dependencias:create", "dependencias:edit", "dependencias:manage"],
  MAGISTRADO_CORTE_SUPREMA: [...judicialView, ...adjudicatorWrite, ...selectionManage, "audiencias:mark_completed", "audiencias:create_minutes", "audiencias:view_dependency", ...selfService, "perfil:publish_profile", "perfil:edit_title", "edicion:take_control", "votos:view", "votos:create", "votos:edit", "votos:sign", "votos:publish", "votos:archive", "votos:print", "sala:view", "sala:send", "sala:register_session", "sala:register_vote", "sala:approve", "sala:return", "sala:publish", "notificaciones:view"],
  MAGISTRADO_TRIBUNAL: [...judicialView, ...adjudicatorWrite, ...selectionManage, "audiencias:mark_completed", "audiencias:create_minutes", "audiencias:view_dependency", ...selfService, "perfil:publish_profile", "perfil:edit_title", "edicion:take_control", "votos:view", "votos:create", "votos:edit", "votos:sign", "votos:publish", "votos:archive", "votos:print", "sala:view", "sala:send", "sala:register_session", "sala:register_vote", "sala:approve", "sala:return", "sala:publish", "notificaciones:view"],
  JUEZ_CIRCUITO: [...judicialView, ...adjudicatorWrite, ...selectionManage, "audiencias:mark_completed", "audiencias:create_minutes", "audiencias:view_dependency", ...selfService, "perfil:publish_profile", "perfil:edit_title"],
  JUEZ_MUNICIPAL: [...judicialView, ...adjudicatorWrite, ...selectionManage, "audiencias:mark_completed", "audiencias:create_minutes", "audiencias:view_dependency", ...selfService, "perfil:publish_profile", "perfil:edit_title"],
  SECRETARIO_GENERAL: [
    ...judicialView, ...selfService, ...selectionManage, "audiencias:mark_completed", "audiencias:create_minutes", "audiencias:view_dependency", "expedientes:create", "expedientes:edit", "expedientes:repartition", "expedientes:assign_ponente",
    "actuaciones:create", "audiencias:create", "audiencias:edit", "audiencias:reschedule", "audiencias:cancel",
    "actas:create", "actas:edit", "actas:finalize", "actas:reopen", "actas:sign", "actas:print",
    "documentos:upload", "documentos:share", "comunicados:view", "comunicados:create", "comunicados:edit", "comunicados:publish",
    "estados:view", "estados:create", "estados:edit", "estados:publish", "enlaces:create", "firmas:sign", "firmas:request", "firmas:revoke",
  ],
  SECRETARIO_DESPACHO: [
    ...judicialView, ...selfService, ...selectionManage, "audiencias:mark_completed", "audiencias:create_minutes", "audiencias:view_dependency", "expedientes:edit", "providencias:create", "providencias:edit", "providencias:print", "actuaciones:create",
    "audiencias:create", "audiencias:edit", "audiencias:reschedule", "audiencias:cancel",
    "actas:create", "actas:edit", "actas:finalize", "actas:reopen", "actas:sign", "actas:print",
    "documentos:upload", "documentos:share", "estados:view", "estados:create", "estados:edit", "estados:publish",
    "enlaces:create", "firmas:sign", "firmas:request", "firmas:revoke",
  ],
  OFICIAL_MAYOR: [...judicialView, ...selfService, "seleccion:view", "seleccion:view_applications", "seleccion:edit_applications", "seleccion:update_application_status", "seleccion:edit_public_message", "seleccion:view_dependency", "elecciones:ver", "elecciones:votar", "elecciones:ver_votos", "elecciones:validar_votos", "elecciones:gestionar_escrutinio", "elecciones:agregar_votos_manuales", "providencias:create", "providencias:edit", "providencias:print", "actuaciones:create", "documentos:upload", "documentos:share"],
  AUXILIAR: [...judicialView, ...selfService, "seleccion:view", "seleccion:view_applications", "seleccion:edit_applications", "seleccion:update_application_status", "seleccion:edit_public_message", "seleccion:view_dependency", "elecciones:ver", "elecciones:votar", "elecciones:ver_votos", "providencias:create", "providencias:edit", "providencias:print", "actuaciones:create", "documentos:upload", "notificaciones:view"],
  RADICADOR: [...selfService, "expedientes:view", "expedientes:create", "expedientes:edit", "documentos:view", "documentos:upload", "documentos:preview", "documentos:download"],
  REPARTO: [...selfService, "expedientes:view", "expedientes:edit", "expedientes:repartition", "expedientes:assign_ponente", "documentos:view", "documentos:preview", "documentos:download"],
  ARCHIVO: [...selfService, "expedientes:view", "expedientes:archive", "documentos:view", "documentos:preview", "documentos:download", "documentos:archive", "actuaciones:view", "audiencias:view", "providencias:view", "providencias:print"],
  GOBERNACION_COMUNICACIONES: [...selfService, "comunicados:view", "comunicados:create", "comunicados:edit", "comunicados:publish"],
  CONSULTA_PUBLICA: [],
};

export const SENSITIVE_PERMISSION_KEYS = new Set<PermissionKey>([
  "expedientes:hard_delete",
  "expedientes:repartition",
  "expedientes:assign_ponente",
  "providencias:hard_delete",
  "actuaciones:hard_delete",
  "audiencias:hard_delete",
  "documentos:hard_delete",
  "comunicados:hard_delete",
  "estados:hard_delete",
  "usuarios:deactivate",
  "usuarios:assign_role",
  "roles:manage",
  "configuracion:manage",
]);

export function permissionKey(resource: PermissionResource, action: PermissionAction) {
  return `${resource}:${action}` as PermissionKey;
}

export function defaultRoleCan(role: AppRole, resource: PermissionResource, action: PermissionAction) {
  return DEFAULT_ROLE_PERMISSION_KEYS[role]?.includes(
    permissionKey(resource, action),
  ) ?? false;
}
