import Link from "next/link";
import { notFound } from "next/navigation";
import { CheckCircle2, CircleAlert, Clock3, Eye } from "lucide-react";
import { reviewElectionVote, validateElectionMapZone } from "@/app/actions/elections";
import { ActionMessage } from "@/components/action-message";
import { AdminPageHeader, MetricCard } from "@/components/admin-page";
import { SubmitButton } from "@/components/submit-button";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { PERMISSIONS, requirePermission } from "@/lib/auth/permissions";
import { VOTE_STATUS_LABELS, statusLabel } from "@/lib/elections";

export default async function ElectionScrutiny({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{error?:string;success?:string;q?:string;status?:string;source?:string}>}){
  const [{id},query,{supabase}]=await Promise.all([params,searchParams,requirePermission(PERMISSIONS.electionsScrutiny)]);
  const [{data:election},{data:votes},{data:options},{data:territorial}]=await Promise.all([supabase.from("elections").select("id,title").eq("id",id).maybeSingle(),supabase.from("election_votes").select("id,receipt_code,source,discord_username,visible_name,status,submitted_at,duplicate_candidate,selected:election_options(candidate_name)").eq("election_id",id).order("submitted_at",{ascending:false}),supabase.from("election_options").select("id,candidate_name,display_order").eq("election_id",id).order("display_order"),supabase.from("election_territorial_results").select("*").eq("election_id",id).in("validation_status",["submitted","pending_validation","validated","rejected","pending_submission","cancelled","published"]).order("submitted_at",{ascending:false})]);
  if(!election)notFound();
  const rows=(votes??[]).filter((v)=>{const text=`${v.receipt_code} ${v.discord_username??""} ${one(v.selected)?.candidate_name??""}`.toLowerCase();return (!query.q||text.includes(query.q.toLowerCase()))&&(!query.status||v.status===query.status)&&(!query.source||v.source===query.source)});
  const count=(status:string)=>votes?.filter((v)=>v.status===status).length??0;
  const territorialCount=(status:string)=>territorial?.filter((zone)=>zone.validation_status===status).length??0;
  return <><AdminPageHeader title="Escrutinio electoral" description={election.title} action={<Button asChild variant="outline"><Link href={`/admin/elecciones/${id}`}>Volver</Link></Button>}/><ActionMessage error={query.error} success={query.success}/>
    <div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Pendientes" value={String(count("pending_validation"))} detail="Votos online/manuales sin validación" icon={<Clock3 className="size-5"/>}/><MetricCard label="Territoriales enviados" value={String(territorialCount("submitted")+territorialCount("pending_validation"))} detail="Mapa electoral en revisión" icon={<Eye className="size-5"/>}/><MetricCard label="Válidos" value={String(count("valid"))} detail="Cuentan en resultados" icon={<CheckCircle2 className="size-5"/>}/><MetricCard label="No válidos" value={String(count("annulled")+count("rejected")+count("duplicate"))} detail="Anulados/rechazados" icon={<CircleAlert className="size-5"/>}/></div>
    <form className="mb-5 grid gap-3 rounded-xl border bg-white p-4 md:grid-cols-4"><Input name="q" defaultValue={query.q} placeholder="Comprobante, Discord u opción"/><select name="status" defaultValue={query.status??""} className="h-9 rounded-md border px-3 text-sm"><option value="">Todos los estados</option>{Object.entries(VOTE_STATUS_LABELS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select name="source" defaultValue={query.source??""} className="h-9 rounded-md border px-3 text-sm"><option value="">Todas las fuentes</option><option value="online">Online</option><option value="manual">Manual</option></select><Button type="submit">Filtrar</Button></form>
    <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full min-w-[980px] text-left text-sm"><thead><tr className="border-b bg-slate-50"><th className="p-3">Comprobante</th><th className="p-3">Fuente</th><th className="p-3">Discord</th><th className="p-3">Opción</th><th className="p-3">Estado</th><th className="p-3">Fecha</th><th className="p-3">Acciones</th></tr></thead><tbody>{rows.map((v)=><tr key={v.id} className="border-b align-top"><td className="p-3 font-mono text-xs">{v.receipt_code}</td><td className="p-3">{v.source}</td><td className="p-3">{v.discord_username??"—"}{v.duplicate_candidate&&<Badge variant="outline" className="ml-2 border-amber-200 bg-amber-50">Posible duplicado</Badge>}</td><td className="p-3">{one(v.selected)?.candidate_name??"—"}</td><td className="p-3"><Badge variant="outline">{statusLabel(VOTE_STATUS_LABELS,v.status)}</Badge></td><td className="p-3">{formatDate(v.submitted_at)}</td><td className="p-3"><div className="flex flex-wrap gap-1">{["valid","observed","annulled","rejected","duplicate"].map((status)=><form key={status} action={reviewElectionVote}><input type="hidden" name="election_id" value={id}/><input type="hidden" name="vote_id" value={v.id}/><input type="hidden" name="status" value={status}/><SubmitButton size="sm" variant="outline" pendingLabel="…">{statusLabel(VOTE_STATUS_LABELS,status)}</SubmitButton></form>)}</div></td></tr>)}</tbody></table>{!rows.length&&<p className="p-8 text-center text-sm text-muted-foreground">No hay votos con los filtros actuales.</p>}</div>
    <section className="mt-6 rounded-xl border bg-white">
      <div className="border-b p-4">
        <h2 className="font-semibold text-[#153553]">Votos territoriales / mapa electoral</h2>
        <p className="mt-1 text-xs text-muted-foreground">Registros enviados desde el mapa. Estos datos solo impactan resultados públicos cuando se validan y luego se publica una actualización.</p>
      </div>
      <div className="overflow-x-auto"><table className="w-full min-w-[1040px] text-left text-sm"><thead><tr className="border-b bg-slate-50"><th className="p-3">Territorio</th><th className="p-3">Avance</th><th className="p-3">Estado</th><th className="p-3">Conteos</th><th className="p-3">Enviado</th><th className="p-3">Acciones</th></tr></thead><tbody>{(territorial??[]).map((zone)=><tr key={zone.id} className="border-b align-top"><td className="p-3"><div className="font-medium">{zone.zone_name}</div><div className="text-xs text-muted-foreground">{zone.department} · {zone.zone_label||zone.zone_type}</div></td><td className="p-3">{Number(zone.counted_percentage).toFixed(2)}%</td><td className="p-3"><Badge variant="outline">{territorialStatusLabel(zone.validation_status)}</Badge></td><td className="p-3 text-xs">{Object.entries((zone.option_counts??{}) as Record<string,number>).map(([key,value])=><div key={key}>{optionName(options??[],key)}: {Number(value).toLocaleString("es-CO")}</div>)}<div>Anulados: {Number(zone.annulled_votes??0).toLocaleString("es-CO")}</div><div>Rechazados/otros: {Number(zone.rejected_votes??0).toLocaleString("es-CO")}</div></td><td className="p-3">{zone.submitted_at?formatDate(zone.submitted_at):"—"}</td><td className="p-3"><div className="flex flex-wrap gap-1">{["submitted","pending_validation"].includes(zone.validation_status)&&<><TerritorialAction id={id} zoneId={zone.id} status="validated" label="Validar"/><TerritorialAction id={id} zoneId={zone.id} status="pending_validation" label="Observar"/><TerritorialAction id={id} zoneId={zone.id} status="pending_submission" label="Devolver"/><TerritorialAction id={id} zoneId={zone.id} status="rejected" label="Rechazar"/></>}</div></td></tr>)}</tbody></table>{!territorial?.length&&<p className="p-8 text-center text-sm text-muted-foreground">No hay datos territoriales enviados al escrutinio.</p>}</div>
    </section>
    <p className="mt-4 text-xs text-muted-foreground">Opciones configuradas: {options?.map((o)=>o.candidate_name).join(" · ")}</p></>;
}
function one<T>(v:T|T[]|null|undefined):T|null{return Array.isArray(v)?v[0]??null:v??null}
function formatDate(value:string){return new Intl.DateTimeFormat("es-CO",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value));}
function optionName(options:Array<{id:string;candidate_name:string;display_order:number}>,key:string){const found=options.find((option)=>option.id===key);return found?`Tarjeta Electoral ${found.display_order} · ${found.candidate_name}`:key}
function territorialStatusLabel(value:string){return ({draft:"Borrador",pending_submission:"Pendiente de envío",submitted:"Enviado al escrutinio",pending_validation:"Pendiente de validación",validated:"Validado",rejected:"Rechazado",cancelled:"Cancelado",published:"Publicado"} as Record<string,string>)[value]??value}
function TerritorialAction({id,zoneId,status,label}:{id:string;zoneId:string;status:string;label:string}){return <form action={validateElectionMapZone}><input type="hidden" name="election_id" value={id}/><input type="hidden" name="zone_id" value={zoneId}/><input type="hidden" name="status" value={status}/><input type="hidden" name="return_to" value="escrutinio"/><SubmitButton size="sm" variant="outline" pendingLabel="…">{label}</SubmitButton></form>}
