import { Building2, Plus } from "lucide-react";
import { AdminPageHeader, EmptyState } from "@/components/admin-page";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { createClient } from "@/lib/supabase/server";

type DependencyRow = { id: string; name: string; code: string; type: string; department: string; municipality: string; is_active: boolean; archived_at: string | null };
type CourtRow = { id: string; official_name: string; abbreviation: string; court_system: string; court_level: string; district: string | null; state_or_territory: string | null; accepted_case_categories: string[] | null; active: boolean };

export default async function DependenciesPage() {
  const supabase = await createClient();
  const [dependencyResult, courtsResult] = supabase ? await Promise.all([
    supabase.from("dependencies").select("id,name,code,type,department,municipality,is_active,archived_at").order("name").limit(100),
    supabase.from("federal_courts").select("id,official_name,abbreviation,court_system,court_level,district,state_or_territory,accepted_case_categories,active").order("court_level").order("official_name").limit(100),
  ]) : [{ data: null }, { data: null }];
  const dependencies = (dependencyResult.data ?? []) as DependencyRow[];
  const courts = (courtsResult.data ?? []) as CourtRow[];
  return <><AdminPageHeader title="Componentes DOJ y Federal Court Directory" description="Componentes internos del Department of Justice y directorio estructurado de tribunales federales para Cases." action={<Button className="gap-2 bg-[#153b5c]"><Plus className="size-4" /> Nuevo componente</Button>} />{dependencies.length === 0 ? <EmptyState title="No hay componentes registrados" description="Cree unidades institucionales para asignar usuarios, Matters y Federal Cases." icon={<Building2 className="size-6" />} /> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{dependencies.map((item) => <article key={item.id} className="rounded-lg border bg-white p-5"><div className="flex items-start justify-between"><div className="grid size-10 place-items-center rounded bg-[#edf2f6] text-[#183d61]"><Building2 className="size-5" /></div><Badge className={item.is_active && !item.archived_at ? "bg-emerald-50 text-emerald-800" : "bg-red-50 text-red-800"}>{item.is_active && !item.archived_at ? "Activo" : "Archivado"}</Badge></div><h2 className="mt-4 text-sm font-semibold text-[#153553]">{item.name}</h2><p className="mono-number mt-2 text-xs text-muted-foreground">Code: {item.code}</p><p className="mt-1 text-xs text-muted-foreground">{item.type} · {item.department} · {item.municipality}</p></article>)}</div>}<section className="mt-8"><h2 className="font-serif text-2xl font-semibold text-[#102d49]">Federal Court Directory</h2><p className="mt-2 text-sm text-muted-foreground">OWNER puede ampliar o retirar cortes configurables con fechas de vigencia; las entradas oficiales sembradas están protegidas.</p><div className="mt-4 grid gap-4 md:grid-cols-2">{courts.length === 0 ? <div className="rounded-lg border bg-white p-6 text-sm text-slate-600">No hay federal courts en el catálogo local.</div> : courts.map((court) => <article key={court.id} className="rounded-lg border bg-white p-5"><div className="flex items-start justify-between gap-3"><div><p className="mono-number text-xs font-semibold text-[#005ea8]">{court.abbreviation}</p><h3 className="mt-2 text-sm font-semibold text-[#153553]">{court.official_name}</h3></div><Badge variant="outline" className={court.active ? "border-emerald-200 bg-emerald-50 text-emerald-800" : "border-slate-200 bg-slate-100"}>{court.active ? "Active" : "Inactive"}</Badge></div><p className="mt-3 text-xs text-muted-foreground">{court.court_system} · {court.district || court.state_or_territory || court.court_level}</p><p className="mt-2 text-xs text-slate-600">Categories: {(court.accepted_case_categories ?? []).join(", ") || "Configurable"}</p></article>)}</div></section></>;
}
