import Link from "next/link";
import { Eye, Plus } from "lucide-react";
import { AdminPageHeader } from "@/components/admin-page";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { proceedings, formatDate } from "@/lib/demo-data";
import { CaseStatusBadge } from "@/components/status-badges";
export default function AdminProceedingsPage() { return <><AdminPageHeader title="Providencias" description="Redacción, revisión, firma y publicación de decisiones judiciales simuladas." action={<Button asChild className="gap-2 bg-[#153b5c]"><Link href="/admin/providencias/nueva"><Plus className="size-4" /> Nueva providencia</Link></Button>} /><div className="rounded-lg border bg-white"><div className="border-b p-4"><Input placeholder="Buscar por número, radicado o título…" className="max-w-xl" /></div><Table><TableHeader><TableRow className="bg-slate-50"><TableHead>Número</TableHead><TableHead>Tipo / título</TableHead><TableHead>Radicado</TableHead><TableHead>Sala</TableHead><TableHead>Fecha</TableHead><TableHead>Estado</TableHead><TableHead /></TableRow></TableHeader><TableBody>{proceedings.map((item) => <TableRow key={item.id}><TableCell className="mono-number text-xs font-semibold">{item.number}</TableCell><TableCell><p className="text-sm font-semibold text-[#153553]">{item.title}</p><p className="mt-1 text-xs text-muted-foreground">{item.type} · {item.judge}</p></TableCell><TableCell className="mono-number text-xs">{item.caseNumber}</TableCell><TableCell className="text-xs">{item.chamber}</TableCell><TableCell className="text-xs">{formatDate(item.date)}</TableCell><TableCell><CaseStatusBadge status={item.status} /></TableCell><TableCell><Button asChild variant="ghost" size="icon"><Link href={`/providencias/${item.id}`}><Eye className="size-4" /></Link></Button></TableCell></TableRow>)}</TableBody></Table></div></>; }
