import { Filter, Plus } from "lucide-react";
import { AdminPageHeader } from "@/components/admin-page";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { actions, cases, formatDate } from "@/lib/demo-data";
import { Badge } from "@/components/ui/badge";
export const metadata = { title: "Actuaciones" };
export default function ActionsPage() { return <><AdminPageHeader title="Actuaciones procesales" description="Registro cronológico global de actuaciones judiciales y administrativas." action={<Button className="gap-2 bg-[#153b5c]"><Plus className="size-4" /> Nueva actuación</Button>} /><div className="rounded-lg border bg-white"><div className="grid gap-3 border-b p-4 sm:grid-cols-[1fr_auto]"><Input placeholder="Buscar actuación, usuario o radicado…" /><Button variant="outline" className="gap-2"><Filter className="size-4" /> Filtros</Button></div><div className="overflow-x-auto"><Table><TableHeader><TableRow className="bg-slate-50"><TableHead>Fecha</TableHead><TableHead>Tipo y descripción</TableHead><TableHead>Expediente</TableHead><TableHead>Creada por</TableHead><TableHead>Visibilidad</TableHead></TableRow></TableHeader><TableBody>{actions.map((item) => { const caseItem = cases.find((c) => c.id === item.caseId); return <TableRow key={item.id}><TableCell className="whitespace-nowrap text-xs">{formatDate(item.date)}</TableCell><TableCell><p className="text-sm font-semibold text-[#153553]">{item.type}</p><p className="mt-1 max-w-md text-xs text-muted-foreground">{item.description}</p></TableCell><TableCell className="mono-number text-xs">{caseItem?.internalNumber}</TableCell><TableCell className="text-xs">{item.user}</TableCell><TableCell><Badge variant="outline" className={item.visibility === "Pública" ? "border-emerald-200 bg-emerald-50 text-emerald-800" : "border-slate-200 bg-slate-100"}>{item.visibility}</Badge></TableCell></TableRow>; })}</TableBody></Table></div></div></>; }
