import Link from "next/link";
import { notFound } from "next/navigation";
import { ExternalLink, Mail, UserRoundSearch } from "lucide-react";
import { updateSelectionApplication } from "@/app/actions/selection";
import { ActionMessage } from "@/components/action-message";
import { AdminPageHeader } from "@/components/admin-page";
import { SelectionProcessForm } from "@/components/selection-process-form";
import { SubmitButton } from "@/components/submit-button";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { can, PERMISSIONS, requirePermission } from "@/lib/auth/permissions";

export default async function SelectionDetail({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{error?:string;success?:string}>}){
  const [{id},query,{supabase,profile}]=await Promise.all([params,searchParams,requirePermission(PERMISSIONS.selectionView)]);
  const [{data:process},canEdit,canViewApplications,canEditApplications,canEvaluate,{data:dependencies},{data:reviewers}]=await Promise.all([
    supabase.from("selection_processes").select("*,dependency:dependencies!selection_processes_dependency_id_fkey(name),institution:dependencies!selection_processes_institution_id_fkey(name),responsible:profiles!selection_processes_responsible_user_id_fkey(full_name,is_owner)").eq("id",id).maybeSingle(),
    can(profile,"edit","seleccion",{supabase}),can(profile,"view_applications","seleccion",{supabase}),can(profile,"edit_applications","seleccion",{supabase}),can(profile,"evaluate_applications","seleccion",{supabase}),
    supabase.from("dependencies").select("id,name,parent_id").eq("is_active",true).is("archived_at",null).order("name"),supabase.from("profiles").select("id,full_name,is_owner").eq("is_active",true).neq("role","CONSULTA_PUBLICA").order("full_name"),
  ]);if(!process)notFound();
  const {data:applications}=canViewApplications?await supabase.from("selection_applications").select("id,applicant_name,applicant_email,applicant_identifier,phone,statement,experience,status,internal_notes,score,reviewed_at,source,created_at").eq("process_id",id).order("created_at",{ascending:false}):{data:[]};
  const dependency=one(process.dependency),institution=one(process.institution),responsible=one(process.responsible);
  return <><AdminPageHeader title={process.title} description={`${process.position_title} · ${dependency?.name??"Sin despacho"}`} action={<div className="flex flex-wrap gap-2">{process.visibility==="publico"&&<Button asChild variant="outline"><Link href={`/convocatorias/${process.slug}`} target="_blank"><ExternalLink className="size-4"/>Convocatoria pública</Link></Button>}<Button asChild variant="outline"><Link href="/admin/seleccion">Volver</Link></Button></div>}/><ActionMessage error={query.error} success={query.success}/>
    <section className="mb-5 grid min-w-0 gap-3 rounded-xl border bg-white p-5 sm:grid-cols-2 xl:grid-cols-4"><Fact label="Estado" value={statusLabel(process.status)}/><Fact label="Institución" value={institution?.name??"Sin institución"}/><Fact label="Despacho" value={dependency?.name??"Sin despacho"}/><Fact label="Responsable" value={responsible?.is_owner?"Lilith D'Amico":responsible?.full_name??"Sin responsable"}/><Fact label="Apertura" value={formatDate(process.opening_at)}/><Fact label="Cierre" value={formatDate(process.closing_at)}/><Fact label="Vacantes" value={String(process.vacancies)}/><Fact label="Visibilidad" value={process.visibility==="publico"?"Pública":"Interna"}/></section>
    {canEdit?<details className="mb-5 rounded-xl border bg-white p-4"><summary className="cursor-pointer font-semibold text-[#153553]">Editar configuración del proceso</summary><div className="mt-4"><SelectionProcessForm dependencies={dependencies??[]} reviewers={reviewers??[]} process={process}/></div></details>:<p className="mb-5 rounded border bg-white p-4 text-sm text-muted-foreground">Puede consultar este proceso, pero no modificarlo.</p>}
    <div className="mb-4 flex min-w-0 flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold text-[#153553]">Postulaciones</h2><p className="text-sm text-muted-foreground">Información privada visible únicamente dentro del alcance autorizado.</p></div><Badge variant="outline">{applications?.length??0} postulaciones</Badge></div>
    {!canViewApplications?<p className="rounded-xl border bg-white p-8 text-center text-sm text-muted-foreground">No tiene permiso para consultar las postulaciones de este proceso.</p>:<div className="space-y-4">{applications?.map((application)=><article key={application.id} className="min-w-0 rounded-xl border bg-white p-5"><div className="flex min-w-0 flex-wrap items-start justify-between gap-3"><div className="min-w-0"><h3 className="break-words font-semibold text-[#153553]">{application.applicant_name}</h3><p className="mt-1 flex min-w-0 items-center gap-1 break-all text-xs text-muted-foreground"><Mail className="size-3 shrink-0"/>{application.applicant_email}</p>{application.applicant_identifier&&<p className="mt-1 break-words text-xs text-muted-foreground">Identificador: {application.applicant_identifier}</p>}</div><Badge variant="outline">{applicationStatus(application.status)}</Badge></div><div className="mt-4 grid gap-4 lg:grid-cols-2"><TextBlock label="Presentación" value={application.statement}/><TextBlock label="Experiencia" value={application.experience||"Sin experiencia adicional registrada."}/></div>{canEditApplications?<form action={updateSelectionApplication} className="mt-4 grid min-w-0 gap-3 rounded-lg border bg-slate-50 p-4 md:grid-cols-[180px_120px_minmax(0,1fr)_auto]"><input type="hidden" name="application_id" value={application.id}/><input type="hidden" name="process_id" value={id}/><label className="grid gap-1 text-xs font-medium">Estado<select name="status" defaultValue={application.status} className="h-9 rounded-md border bg-white px-2 text-sm">{applicationStatuses.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="grid gap-1 text-xs font-medium">Puntaje<Input name="score" type="number" min={0} max={100} step="0.01" defaultValue={application.score??""} disabled={!canEvaluate}/></label><label className="grid gap-1 text-xs font-medium">Notas internas<Textarea name="internal_notes" defaultValue={application.internal_notes??""} disabled={!canEvaluate} className="min-h-20 bg-white"/></label><div className="flex items-end"><SubmitButton pendingLabel="Guardando…">Actualizar</SubmitButton></div></form>:<p className="mt-4 text-xs text-muted-foreground">Consulta únicamente; no tiene permiso para cambiar el estado o la evaluación.</p>}</article>)}{!applications?.length&&<p className="rounded-xl border border-dashed bg-white p-10 text-center text-sm text-muted-foreground"><UserRoundSearch className="mx-auto mb-3 size-8"/>Aún no hay postulaciones para este proceso.</p>}</div>}
  </>;
}
const applicationStatuses=[["recibida","Recibida"],["en_revision","En revisión"],["preseleccionada","Preseleccionada"],["rechazada","Rechazada"],["entrevista","Entrevista"],["aceptada","Aceptada"],["archivada","Archivada"]] as const;
function applicationStatus(value:string){return applicationStatuses.find(([key])=>key===value)?.[1]??value}function statusLabel(value:string){return ({borrador:"Borrador",abierto:"Abierto",cerrado:"Cerrado",en_revision:"En revisión",preseleccion:"Preselección",entrevistas:"Entrevistas",finalizado:"Finalizado",cancelado:"Cancelado",archivado:"Archivado"} as Record<string,string>)[value]??value}function one<T>(value:T|T[]|null):T|null{return Array.isArray(value)?value[0]??null:value}function Fact({label,value}:{label:string;value:string}){return <div className="min-w-0"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 break-words text-sm">{value}</p></div>}function TextBlock({label,value}:{label:string;value:string}){return <div className="min-w-0"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 whitespace-pre-wrap break-words text-sm">{value}</p></div>}function formatDate(value:string){return new Intl.DateTimeFormat("es-CO",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value));}
