"use client";
import { useActionState } from "react";
import { CheckCircle2, Search, ShieldCheck } from "lucide-react";
import { lookupSelectionApplicationStatus, type ApplicationLookupState } from "@/app/actions/selection";
import { SubmitButton } from "@/components/submit-button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
const initialState:ApplicationLookupState={};
const labels:Record<string,string>={recibida:"Recibida",en_revision:"En revisión",preseleccionada:"Preseleccionada",rechazada:"No seleccionada",entrevista:"Entrevista",aceptada:"Aceptada",archivada:"Archivada",proceso_cerrado:"Proceso cerrado",proceso_cancelado:"Proceso cancelado"};
const messages:Record<string,string>={recibida:"Su postulación fue recibida correctamente.",en_revision:"Su postulación está siendo revisada por el despacho.",preseleccionada:"Su postulación avanzó a la etapa de preselección.",entrevista:"Su postulación fue marcada para entrevista. Esté atento a las instrucciones oficiales.",aceptada:"Su postulación fue aceptada.",rechazada:"Su postulación no fue seleccionada en esta etapa.",archivada:"Su postulación fue archivada.",proceso_cerrado:"El proceso ya fue cerrado.",proceso_cancelado:"El proceso fue cancelado."};
export function ApplicationStatusLookup(){const [state,action]=useActionState(lookupSelectionApplicationStatus,initialState);return <div className="grid gap-6 lg:grid-cols-[380px_minmax(0,1fr)]"><form action={action} className="grid h-fit gap-4 rounded-xl border bg-white p-6"><div><h2 className="font-semibold text-[#153553]">Consultar postulación</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">Ingrese el código recibido y el mismo correo usado al postularse.</p></div><label className="grid gap-2 text-sm font-medium">Código de seguimiento<Input name="tracking_code" required maxLength={40} autoComplete="off" placeholder="POST-2026-…" className="font-mono uppercase"/></label><label className="grid gap-2 text-sm font-medium">Correo de la postulación<Input name="email" type="email" required maxLength={320} autoComplete="email"/></label>{state.error&&<p role="alert" className="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-800">{state.error}</p>}<SubmitButton pendingLabel="Consultando…"><Search className="size-4"/>Consultar estado</SubmitButton><p className="flex items-start gap-2 text-[11px] leading-5 text-muted-foreground"><ShieldCheck className="mt-0.5 size-3.5 shrink-0"/>El correo por sí solo nunca revela si existe una postulación.</p></form><div>{state.result?<StatusResult result={state.result}/>:<div className="grid min-h-72 place-items-center rounded-xl border border-dashed bg-white p-8 text-center"><div><Search className="mx-auto size-9 text-slate-400"/><p className="mt-3 font-medium text-[#153553]">El resultado aparecerá aquí</p><p className="mt-1 text-sm text-muted-foreground">No se muestran notas internas, puntajes ni datos de evaluadores.</p></div></div>}</div></div>}
function StatusResult({result}:{result:NonNullable<ApplicationLookupState["result"]>}){return <article className="min-w-0 rounded-xl border bg-white p-6 shadow-sm"><div className="flex min-w-0 flex-wrap items-start justify-between gap-3"><div className="min-w-0"><p className="text-xs font-semibold uppercase tracking-wide text-[#9a752f]">{result.positionTitle}</p><h2 className="mt-1 break-words text-lg font-semibold text-[#153553]">{result.processTitle}</h2><p className="mt-2 break-words text-sm text-muted-foreground">{result.institutionName} · {result.dependencyName}</p></div><Badge variant="outline" className="border-emerald-200 bg-emerald-50 text-emerald-800">{labels[result.status]??"En trámite"}</Badge></div><div className="mt-6 rounded-lg border border-emerald-200 bg-emerald-50 p-4"><p className="flex items-start gap-2 text-sm font-medium text-emerald-950"><CheckCircle2 className="mt-0.5 size-4 shrink-0"/>{messages[result.status]??"Consulte más adelante para conocer novedades."}</p>{result.message&&<div className="mt-3 border-t border-emerald-200 pt-3"><p className="text-xs font-semibold uppercase tracking-wide text-emerald-900">Mensaje del despacho</p><p className="mt-1 whitespace-pre-wrap break-words text-sm text-emerald-950">{result.message}</p></div>}</div><dl className="mt-5 grid gap-4 text-sm sm:grid-cols-2"><Fact label="Postulante" value={result.applicantName}/><Fact label="Presentada" value={formatDate(result.submittedAt)}/><Fact label="Estado público" value={labels[result.status]??"En trámite"}/><Fact label="Última actualización pública" value={formatDate(result.updatedAt)}/></dl></article>}
function Fact({label,value}:{label:string;value:string}){return <div className="min-w-0"><dt className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{label}</dt><dd className="mt-1 break-words">{value}</dd></div>}function formatDate(value:string){return new Intl.DateTimeFormat("es-CO",{dateStyle:"long",timeStyle:"short"}).format(new Date(value));}
