import Link from "next/link";
import { saveHearing } from "@/app/actions/hearings";
import { SubmitButton } from "@/components/submit-button";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
type CaseOption = { id: string; internal_number: string };
type Hearing = { id: string; case_id: string; title: string; hearing_type: string; scheduled_at: string; end_at: string | null; room: string; virtual_link: string | null; status: string; participants: unknown; notes: string | null; is_public: boolean };
export function HearingForm({ cases, hearing, initialCaseId }: { cases: CaseOption[]; hearing?: Hearing; initialCaseId?: string }) { const participants = Array.isArray(hearing?.participants) ? hearing.participants.map((p) => typeof p === "string" ? p : (p as { name?: string }).name ?? "").join("\n") : ""; const local = (value?: string | null) => value ? new Date(value).toISOString().slice(0, 16) : ""; return <form action={saveHearing} className="grid max-w-4xl gap-5 rounded-lg border bg-white p-6 md:grid-cols-2">{hearing && <input type="hidden" name="hearing_id" value={hearing.id} />}<Field label="Expediente"><select name="case_id" defaultValue={hearing?.case_id ?? initialCaseId} required className="h-9 rounded-md border px-3 text-sm"><option value="">Seleccione…</option>{cases.map((c) => <option key={c.id} value={c.id}>{c.internal_number}</option>)}</select></Field><Field label="Tipo"><Input name="hearing_type" defaultValue={hearing?.hearing_type} required /></Field><Field label="Título"><Input name="title" defaultValue={hearing?.title} required /></Field><Field label="Sala física"><Input name="room" defaultValue={hearing?.room} required /></Field><Field label="Inicio"><Input type="datetime-local" name="scheduled_at" defaultValue={local(hearing?.scheduled_at)} required /></Field><Field label="Fin"><Input type="datetime-local" name="end_at" defaultValue={local(hearing?.end_at)} /></Field><Field label="Enlace virtual"><Input type="url" name="virtual_link" defaultValue={hearing?.virtual_link ?? ""} /></Field><Field label="Estado"><select name="status" defaultValue={hearing?.status ?? "Programada"} className="h-9 rounded-md border px-3 text-sm">{["Programada", "Reprogramada", "Realizada", "Cancelada"].map((s) => <option key={s}>{s}</option>)}</select></Field><Field label="Visibilidad"><select name="is_public" defaultValue={String(hearing?.is_public ?? false)} className="h-9 rounded-md border px-3 text-sm"><option value="false">Interna</option><option value="true">Pública</option></select></Field><div className="md:col-span-2"><Field label="Participantes (uno por línea)"><Textarea name="participants" defaultValue={participants} /></Field></div><div className="md:col-span-2"><Field label="Notas"><Textarea name="notes" defaultValue={hearing?.notes ?? ""} /></Field></div><div className="flex justify-end gap-3 md:col-span-2"><Button asChild variant="outline"><Link href="/admin/audiencias">Cancelar</Link></Button><SubmitButton pendingLabel="Guardando…">{hearing ? "Guardar cambios" : "Programar audiencia"}</SubmitButton></div></form>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="grid gap-2"><Label>{label}</Label>{children}</div>; }
