"use client";
import { useState } from "react";
import { templates } from "@/lib/providence-templates";
import { MarkdownEditor } from "@/components/markdown-editor";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Save } from "lucide-react";

export function ProvidenceForm() { const names = Object.keys(templates); const [selected, setSelected] = useState(names[0]); return <form className="space-y-5" onSubmit={(e) => e.preventDefault()}><div className="rounded-lg border bg-white p-6"><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4"><Field label="Federal Case"><select className="h-9 w-full rounded-md border px-3 text-sm" required><option value="">Seleccione un Case</option></select></Field><Field label="Tipo / plantilla"><select value={selected} onChange={(e) => setSelected(e.target.value)} className="h-9 w-full rounded-md border px-3 text-sm">{names.map((name) => <option key={name}>{name}</option>)}</select></Field><Field label="Order number"><Input placeholder="Se genera al guardar" /></Field><Field label="Federal court"><Input placeholder="Court or Clerk’s Office" /></Field><Field label="Título"><Input defaultValue={selected} /></Field><Field label="Issuing judge / official"><Input placeholder="Funcionario responsable" /></Field><Field label="Estado"><select className="h-9 w-full rounded-md border px-3 text-sm"><option>Draft</option><option>Under review</option><option>Signed</option><option>Published</option></select></Field><Field label="Visibility"><select className="h-9 w-full rounded-md border px-3 text-sm"><option>Internal</option><option>Public</option><option>Restricted</option><option>Sealed</option></select></Field></div></div><div className="rounded-lg border bg-white p-6"><Label className="mb-3 block">Order / decision content</Label><MarkdownEditor key={selected} initialValue={templates[selected]} /></div><div className="flex justify-end"><Button className="gap-2 bg-[#153b5c]"><Save className="size-4" /> Guardar borrador</Button></div></form>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }
