"use client";
import { useState } from "react";
import { FileSearch, LoaderCircle, Search } from "lucide-react";
import { formatDate } from "@/lib/display";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { CaseStatusBadge } from "@/components/status-badges";
import { Alert, AlertDescription } from "@/components/ui/alert";

type Lookup = { case: { caseNumber: string; docketNumber: string | null; filingStatus: string; court: string; caseCaption: string; caseCategory: string; status: string; filedAt: string } | null; latest: { title: string; description: string; date: string } | null };

export function PublicCaseSearch() {
  const [query, setQuery] = useState(""); const [result, setResult] = useState<Lookup | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  async function search(value = query) { setLoading(true); setError(""); setResult(null); try { const response = await fetch(`/api/public/cases?q=${encodeURIComponent(value.trim())}`); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "No fue posible consultar"); setResult(data); } catch (caught) { setError(caught instanceof Error ? caught.message : "No fue posible consultar"); } finally { setLoading(false); } }
  return <div><form onSubmit={(e) => { e.preventDefault(); void search(); }} className="rounded-lg border bg-white p-5 shadow-sm sm:p-7"><label htmlFor="case-number" className="text-sm font-semibold text-[#153553]">Case Number o Docket Number</label><p className="mt-1 text-xs text-muted-foreground">Ingrese el Case Number del portal o el Docket Number del tribunal si ya fue asignado.</p><div className="mt-4 flex flex-col gap-3 sm:flex-row"><Input id="case-number" value={query} onChange={(e) => { setQuery(e.target.value); setResult(null); }} className="mono-number h-11" placeholder="RP-CR-2026-100001" /><Button type="submit" disabled={loading || !query.trim()} className="h-11 gap-2 bg-[#153b5c]">{loading ? <LoaderCircle className="size-4 animate-spin" /> : <Search className="size-4" />} Consultar</Button></div></form>
    {(error || (result && !result.case)) && <Alert className="mt-6 border-amber-200 bg-amber-50"><FileSearch className="size-4" /><AlertDescription>{error || "No encontramos un Federal Case público con ese identificador. Verifique el número o el nivel de acceso."}</AlertDescription></Alert>}
    {result?.case && <div className="mt-6 overflow-hidden rounded-lg border bg-white"><div className="flex flex-col justify-between gap-4 border-b bg-[#f7f9fb] p-6 sm:flex-row sm:items-start"><div><p className="text-xs font-semibold uppercase tracking-wider text-[#9b762f]">Resultado de consulta</p><h2 className="mono-number mt-2 text-lg font-semibold text-[#102d49]">{result.case.caseNumber}</h2><p className="mono-number mt-1 text-xs text-muted-foreground">{result.case.docketNumber || "No Docket Number publicly recorded"}</p></div><CaseStatusBadge status={result.case.status} /></div><dl className="grid gap-px bg-border sm:grid-cols-2"><ResultField label="Federal court" value={result.case.court} /><ResultField label="Case Category" value={result.case.caseCategory} /><ResultField label="Caption" value={result.case.caseCaption} /><ResultField label="Opened" value={formatDate(result.case.filedAt)} /><ResultField label="Current status" value={result.case.status} /><ResultField label="Filing status" value={result.case.filingStatus || "Awaiting Clerk docketing"} /><div className="bg-white p-5 sm:col-span-2"><dt className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">Latest public docket/event</dt><dd className="mt-2 text-sm font-medium text-[#153553]">{result.latest?.title ?? "No public docket events"}</dd>{result.latest && <p className="mt-1 text-sm text-muted-foreground">{result.latest.description} · {formatDate(result.latest.date)}</p>}</div></dl><div className="border-t bg-slate-50 p-4 text-xs leading-5 text-muted-foreground">La consulta omite Matters internos, notas, datos de identificación, participantes sealed y documentos restringidos.</div></div>}
  </div>;
}
function ResultField({ label, value }: { label: string; value: string }) { return <div className="bg-white p-5"><dt className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">{label}</dt><dd className="mt-2 text-sm font-medium text-[#153553]">{value}</dd></div>; }
