"use client";
import { useState } from "react";
import { FileSearch, LoaderCircle, Search } from "lucide-react";
import { formatDate } from "@/lib/demo-data";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { CaseStatusBadge } from "@/components/status-badges";
import { Alert, AlertDescription } from "@/components/ui/alert";

type Lookup = { case: { internalNumber: string; judicialNumber: string; court: string; processType: string; processSubtype: string; status: string; filedAt: string } | null; latest: { title: string; description: string; date: string } | null };

export function PublicCaseSearch() {
  const [query, setQuery] = useState(""); const [result, setResult] = useState<Lookup | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  async function search(value = query) { setLoading(true); setError(""); setResult(null); try { const response = await fetch(`/api/public/cases?radicado=${encodeURIComponent(value.trim())}`); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "No fue posible consultar"); setResult(data); } catch (caught) { setError(caught instanceof Error ? caught.message : "No fue posible consultar"); } finally { setLoading(false); } }
  return <div><form onSubmit={(e) => { e.preventDefault(); void search(); }} className="rounded-lg border bg-white p-5 shadow-sm sm:p-7"><label htmlFor="case-number" className="text-sm font-semibold text-[#153553]">Número de radicado</label><p className="mt-1 text-xs text-muted-foreground">Ingrese el radicado interno o judicial completo.</p><div className="mt-4 flex flex-col gap-3 sm:flex-row"><Input id="case-number" value={query} onChange={(e) => { setQuery(e.target.value); setResult(null); }} className="mono-number h-11" placeholder="Ej. TSJ-SP-2026-000001" /><Button type="submit" disabled={loading} className="h-11 gap-2 bg-[#153b5c]">{loading ? <LoaderCircle className="size-4 animate-spin" /> : <Search className="size-4" />} Consultar</Button></div><button type="button" onClick={() => { const demo = "TSJ-SP-2026-000001"; setQuery(demo); void search(demo); }} className="mt-3 text-xs font-medium text-[#8a6828] underline underline-offset-2">Usar radicado de demostración</button></form>
    {(error || (result && !result.case)) && <Alert className="mt-6 border-amber-200 bg-amber-50"><FileSearch className="size-4" /><AlertDescription>{error || "No encontramos un expediente público con ese radicado. Verifique el número o el nivel de reserva."}</AlertDescription></Alert>}
    {result?.case && <div className="mt-6 overflow-hidden rounded-lg border bg-white"><div className="flex flex-col justify-between gap-4 border-b bg-[#f7f9fb] p-6 sm:flex-row sm:items-start"><div><p className="text-xs font-semibold uppercase tracking-wider text-[#9b762f]">Resultado de consulta</p><h2 className="mono-number mt-2 text-lg font-semibold text-[#102d49]">{result.case.internalNumber}</h2><p className="mono-number mt-1 text-xs text-muted-foreground">{result.case.judicialNumber}</p></div><CaseStatusBadge status={result.case.status} /></div><dl className="grid gap-px bg-border sm:grid-cols-2"><ResultField label="Despacho" value={result.case.court} /><ResultField label="Clase de proceso" value={`${result.case.processType} · ${result.case.processSubtype}`} /><ResultField label="Fecha de radicación" value={formatDate(result.case.filedAt)} /><ResultField label="Estado actual" value={result.case.status} /><div className="bg-white p-5 sm:col-span-2"><dt className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">Última actuación pública</dt><dd className="mt-2 text-sm font-medium text-[#153553]">{result.latest?.title ?? "Sin actuaciones públicas"}</dd>{result.latest && <p className="mt-1 text-sm text-muted-foreground">{result.latest.description} · {formatDate(result.latest.date)}</p>}</div></dl><div className="border-t bg-slate-50 p-4 text-xs leading-5 text-muted-foreground">La consulta omite documentos internos, datos de identificación y actuaciones reservadas.</div></div>}
  </div>;
}
function ResultField({ label, value }: { label: string; value: string }) { return <div className="bg-white p-5"><dt className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">{label}</dt><dd className="mt-2 text-sm font-medium text-[#153553]">{value}</dd></div>; }
