"use client";
import { useState } from "react";
import { FileSearch, LoaderCircle, Search } from "lucide-react";
import { formatDate } from "@/lib/demo-data";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { CaseStatusBadge } from "@/components/status-badges";
import { Alert, AlertDescription } from "@/components/ui/alert";

type Lookup = { case: { internalNumber: string; judicialNumber: string; court: string; processType: string; processSubtype: string; status: string; filedAt: string } | null; actions: { id: string; title: string; description: string; action_date: string }[]; hearings: { id: string; title: string; scheduled_at: string; room: string; status: string }[]; proceedings: { id: string; providence_number: string; title: string; published_at: string }[] };

export function PublicCaseSearch() {
  const [query, setQuery] = useState(""); const [result, setResult] = useState<Lookup | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  async function search(value = query) { setLoading(true); setError(""); setResult(null); try { const response = await fetch(`/api/public/cases?radicado=${encodeURIComponent(value.trim())}`); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "No fue posible consultar"); setResult(data); } catch (caught) { setError(caught instanceof Error ? caught.message : "No fue posible consultar"); } finally { setLoading(false); } }
  return <div><form onSubmit={(e) => { e.preventDefault(); void search(); }} className="rounded-lg border bg-white p-5 shadow-sm sm:p-7"><label htmlFor="case-number" className="text-sm font-semibold text-[#153553]">Radicado o providencia</label><p className="mt-1 text-xs text-muted-foreground">Ingrese el número interno, radicado judicial o número de providencia completo.</p><div className="mt-4 flex flex-col gap-3 sm:flex-row"><Input id="case-number" value={query} onChange={(e) => { setQuery(e.target.value); setResult(null); }} className="mono-number h-11" placeholder="Ej. CSJ-2026-000001" /><Button type="submit" disabled={loading} className="h-11 gap-2 bg-[#153b5c]">{loading ? <LoaderCircle className="size-4 animate-spin" /> : <Search className="size-4" />} Consultar</Button></div></form>
    {(error || (result && !result.case)) && <Alert className="mt-6 border-amber-200 bg-amber-50"><FileSearch className="size-4" /><AlertDescription>{error || "No encontramos un expediente público con ese radicado. Verifique el número o el nivel de reserva."}</AlertDescription></Alert>}
    {result?.case && <div className="mt-6 overflow-hidden rounded-lg border bg-white"><div className="flex flex-col justify-between gap-4 border-b bg-[#f7f9fb] p-6 sm:flex-row sm:items-start"><div><p className="text-xs font-semibold uppercase tracking-wider text-[#9b762f]">Resultado público</p><h2 className="mono-number mt-2 text-lg font-semibold text-[#102d49]">{result.case.internalNumber}</h2><p className="mono-number mt-1 text-xs text-muted-foreground">{result.case.judicialNumber}</p></div><CaseStatusBadge status={result.case.status} /></div><dl className="grid gap-px bg-border sm:grid-cols-2"><ResultField label="Despacho" value={result.case.court} /><ResultField label="Clase de proceso" value={`${result.case.processType} · ${result.case.processSubtype}`} /><ResultField label="Fecha de radicación" value={formatDate(result.case.filedAt)} /><ResultField label="Estado actual" value={result.case.status} /></dl><PublicList title="Actuaciones públicas" items={result.actions.map((a) => `${formatDate(a.action_date)} · ${a.title} — ${a.description}`)} /><PublicList title="Audiencias públicas" items={result.hearings.map((h) => `${formatDate(h.scheduled_at)} · ${h.title} · ${h.room} · ${h.status}`)} /><PublicList title="Providencias publicadas" items={result.proceedings.map((p) => `${p.providence_number} · ${p.title} · ${formatDate(p.published_at)}`)} /><div className="border-t bg-slate-50 p-4 text-xs leading-5 text-muted-foreground">La consulta omite partes, documentos internos, usuarios y actuaciones reservadas.</div></div>}
  </div>;
}
function ResultField({ label, value }: { label: string; value: string }) { return <div className="bg-white p-5"><dt className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">{label}</dt><dd className="mt-2 text-sm font-medium text-[#153553]">{value}</dd></div>; }
function PublicList({ title, items }: { title: string; items: string[] }) { return <section className="border-t p-5"><h3 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">{title}</h3><div className="mt-3 space-y-2">{items.length ? items.map((item) => <p key={item} className="rounded border p-3 text-sm">{item}</p>) : <p className="text-sm text-muted-foreground">Sin información pública.</p>}</div></section>; }
