import Link from "next/link";
import { saveSelectionProcess } from "@/app/actions/selection";
import { DraftForm } from "@/components/draft-form";
import { SubmitButton } from "@/components/submit-button";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

type Dependency={id:string;name:string;parent_id:string|null};type Reviewer={id:string;full_name:string;is_owner:boolean};
type Process={id:string;institution_id:string;dependency_id:string;title:string;position_title:string;description:string;requirements:string;responsibilities:string|null;opening_at:string;closing_at:string;status:string;vacancies:number;visibility:string;application_instructions:string|null;responsible_user_id:string|null};
export function SelectionProcessForm({dependencies,reviewers,process}:{dependencies:Dependency[];reviewers:Reviewer[];process?:Process}){
  const roots=dependencies.filter((item)=>!item.parent_id);const local=(value:string)=>new Date(value).toISOString().slice(0,16);
  return <DraftForm action={saveSelectionProcess} storageKey={`sigj:selection:${process?.id??"new"}`} className="grid min-w-0 gap-5 rounded-xl border bg-white p-5 md:grid-cols-2">
    {process&&<input type="hidden" name="process_id" value={process.id}/>}<Field label="Institución *"><select name="institution_id" required defaultValue={process?.institution_id??""} className="h-9 min-w-0 rounded-md border px-3 text-sm"><option value="">Seleccione…</option>{roots.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Despacho o dependencia *"><select name="dependency_id" required defaultValue={process?.dependency_id??""} className="h-9 min-w-0 rounded-md border px-3 text-sm"><option value="">Seleccione…</option>{dependencies.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field>
    <Field label="Nombre del proceso *"><Input name="title" required maxLength={180} defaultValue={process?.title} placeholder="Convocatoria de auxiliar judicial 2026"/></Field><Field label="Cargo ofrecido *"><Input name="position_title" required maxLength={160} defaultValue={process?.position_title} placeholder="Auxiliar judicial"/></Field>
    <div className="md:col-span-2"><Field label="Descripción *"><Textarea name="description" required defaultValue={process?.description} className="min-h-28"/></Field></div><div className="md:col-span-2"><Field label="Requisitos *"><Textarea name="requirements" required defaultValue={process?.requirements} className="min-h-28"/></Field></div><div className="md:col-span-2"><Field label="Responsabilidades"><Textarea name="responsibilities" defaultValue={process?.responsibilities??""}/></Field></div>
    <Field label="Apertura *"><Input type="datetime-local" name="opening_at" required defaultValue={process?local(process.opening_at):""}/></Field><Field label="Cierre *"><Input type="datetime-local" name="closing_at" required defaultValue={process?local(process.closing_at):""}/></Field>
    <Field label="Estado"><select name="status" defaultValue={process?.status??"borrador"} className="h-9 rounded-md border px-3 text-sm">{[["borrador","Borrador"],["abierto","Abierto"],["cerrado","Cerrado"],["en_revision","En revisión"],["preseleccion","Preselección"],["entrevistas","Entrevistas"],["finalizado","Finalizado"],["cancelado","Cancelado"]].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><Field label="Visibilidad"><select name="visibility" defaultValue={process?.visibility??"interno"} className="h-9 rounded-md border px-3 text-sm"><option value="interno">Solo interna</option><option value="publico">Convocatoria pública</option></select></Field>
    <Field label="Número de vacantes"><Input type="number" name="vacancies" min={1} max={100} required defaultValue={process?.vacancies??1}/></Field><Field label="Responsable"><select name="responsible_user_id" defaultValue={process?.responsible_user_id??""} className="h-9 min-w-0 rounded-md border px-3 text-sm"><option value="">Sin responsable específico</option>{reviewers.map((item)=><option key={item.id} value={item.id}>{item.is_owner?"Lilith D'Amico":item.full_name}</option>)}</select></Field>
    <div className="md:col-span-2"><Field label="Instrucciones para postular"><Textarea name="application_instructions" defaultValue={process?.application_instructions??""}/></Field></div><p className="text-xs text-muted-foreground md:col-span-2">Una convocatoria pública solo acepta postulaciones mientras esté abierta y dentro de las fechas configuradas. Las notas y evaluaciones nunca son públicas.</p>
    <div className="flex flex-wrap justify-end gap-3 md:col-span-2"><Button asChild variant="outline"><Link href={process?`/admin/seleccion/${process.id}`:"/admin/seleccion"}>Cancelar</Link></Button><SubmitButton pendingLabel="Guardando…">{process?"Guardar proceso":"Crear proceso"}</SubmitButton></div>
  </DraftForm>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="grid min-w-0 gap-2 text-sm"><span className="font-medium">{label}</span>{children}</label>}
