import Link from "next/link";
import { BriefcaseBusiness, ClipboardList, Plus, Search, UserRoundCheck } from "lucide-react";
import { ActionMessage } from "@/components/action-message";
import { AdminPageHeader, MetricCard } from "@/components/admin-page";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { can, PERMISSIONS, requirePermission } from "@/lib/auth/permissions";

type Query={q?:string;status?:string;dependency?:string;institution?:string;error?:string;success?:string};
export default async function SelectionPage({searchParams}:{searchParams:Promise<Query>}){
  const [{supabase,profile},query]=await Promise.all([requirePermission(PERMISSIONS.selectionView),searchParams]);
  const [canCreate,{data:processes,error},{data:dependencies}]=await Promise.all([can(profile,"create","seleccion",{supabase}),supabase.from("selection_processes").select("id,slug,title,position_title,status,visibility,opening_at,closing_at,vacancies,dependency:dependencies!selection_processes_dependency_id_fkey(id,name),institution:dependencies!selection_processes_institution_id_fkey(id,name),applications:selection_applications(id,status)").order("created_at",{ascending:false}).limit(300),supabase.from("dependencies").select("id,name,parent_id").eq("is_active",true).is("archived_at",null).order("name")]);
  const normalized=(query.q??"").trim().toLocaleLowerCase("es");const rows=(processes??[]).filter((item)=>{const dependency=one(item.dependency);const institution=one(item.institution);return (!normalized||`${item.title} ${item.position_title} ${dependency?.name} ${institution?.name}`.toLocaleLowerCase("es").includes(normalized))&&(!query.status||item.status===query.status)&&(!query.dependency||(dependency as {id?:string}|null)?.id===query.dependency)&&(!query.institution||(institution as {id?:string}|null)?.id===query.institution);});
  const totalApplications=rows.reduce((sum,item)=>sum+(item.applications?.length??0),0),pending=rows.reduce((sum,item)=>sum+(item.applications?.filter((application)=>application.status==="recibida").length??0),0);
  const scopeTitle=profile.is_owner?"Todos los procesos":profile.role==="ADMIN_INSTITUCIONAL"?"Procesos de mi institución":"Procesos de mi despacho";
  return <><AdminPageHeader title="Procesos de selección" description={`${scopeTitle}. Las postulaciones se aíslan por despacho y alcance institucional.`} action={canCreate?<Button asChild><Link href="/admin/seleccion/nuevo"><Plus className="size-4"/>Crear proceso</Link></Button>:<Button disabled title="No tiene permiso para crear procesos"><Plus className="size-4"/>Crear proceso</Button>}/><ActionMessage error={query.error??(error?"No fue posible consultar los procesos.":undefined)} success={query.success}/>
    <div className="mb-5 grid gap-3 sm:grid-cols-3"><MetricCard label="Procesos visibles" value={String(rows.length)} detail={scopeTitle} icon={<BriefcaseBusiness className="size-5"/>}/><MetricCard label="Postulaciones" value={String(totalApplications)} detail="En procesos visibles y autorizados" icon={<ClipboardList className="size-5"/>}/><MetricCard label="Por revisar" value={String(pending)} detail="Postulaciones recién recibidas" icon={<UserRoundCheck className="size-5"/>}/></div>
    <form className="mb-5 grid gap-3 rounded-xl border bg-white p-4 md:grid-cols-2 xl:grid-cols-5"><label className="grid gap-1 text-xs font-medium md:col-span-2">Buscar proceso<Input name="q" defaultValue={query.q} placeholder="Cargo, proceso, despacho o institución…"/></label><Filter label="Estado" name="status" value={query.status}><option value="">Todos</option>{statuses.map(([value,label])=><option key={value} value={value}>{label}</option>)}</Filter><Filter label="Despacho" name="dependency" value={query.dependency}><option value="">Todos los despachos</option>{dependencies?.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</Filter><Filter label="Institución" name="institution" value={query.institution}><option value="">Todas las instituciones</option>{dependencies?.filter((item)=>!item.parent_id).map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</Filter><div className="flex flex-wrap gap-2 md:col-span-2 xl:col-span-5"><Button type="submit"><Search className="size-4"/>Filtrar</Button><Button asChild variant="outline"><Link href="/admin/seleccion">Limpiar</Link></Button></div></form>
    <div className="grid min-w-0 gap-4 lg:grid-cols-2">{rows.map((process)=>{const dependency=one(process.dependency),institution=one(process.institution),applications=process.applications??[];return <article key={process.id} className="min-w-0 rounded-xl border bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex min-w-0 flex-wrap items-start justify-between gap-3"><div className="min-w-0 flex-1"><p className="break-words text-xs font-semibold uppercase tracking-wide text-[#9a752f]">{process.position_title}</p><h2 className="mt-1 break-words font-semibold text-[#153553]">{process.title}</h2></div><Badge variant="outline">{statusLabel(process.status)}</Badge></div><p className="mt-3 break-words text-xs text-muted-foreground">{dependency?.name??"Sin despacho"} · {institution?.name??"Sin institución"}</p><div className="mt-4 grid grid-cols-3 gap-2 text-center text-xs"><Stat value={process.vacancies} label="Vacantes"/><Stat value={applications.length} label="Postulaciones"/><Stat value={applications.filter((item)=>item.status==="recibida").length} label="Por revisar"/></div><div className="mt-4 flex flex-wrap gap-2"><Button asChild size="sm"><Link href={`/admin/seleccion/${process.id}`}>Abrir proceso</Link></Button>{process.visibility==="publico"&&<Button asChild size="sm" variant="outline"><Link href={`/convocatorias/${process.slug}`} target="_blank">Vista pública</Link></Button>}</div></article>})}</div>{!rows.length&&<p className="rounded-xl border border-dashed bg-white p-10 text-center text-sm text-muted-foreground">No hay procesos de selección dentro de los filtros y alcance actuales.</p>}
  </>;
}
const statuses=[["borrador","Borrador"],["abierto","Abierto"],["cerrado","Cerrado"],["en_revision","En revisión"],["preseleccion","Preselección"],["entrevistas","Entrevistas"],["finalizado","Finalizado"],["cancelado","Cancelado"],["archivado","Archivado"]] as const;
function statusLabel(value:string){return statuses.find(([key])=>key===value)?.[1]??value}function one<T>(value:T|T[]|null):T|null{return Array.isArray(value)?value[0]??null:value}function Stat({value,label}:{value:number;label:string}){return <div className="min-w-0 rounded bg-slate-50 p-2"><strong className="block text-base text-[#153553]">{value}</strong><span className="break-words text-muted-foreground">{label}</span></div>}function Filter({label,name,value,children}:{label:string;name:string;value?:string;children:React.ReactNode}){return <label className="grid min-w-0 gap-1 text-xs font-medium">{label}<select name={name} defaultValue={value??""} className="h-9 min-w-0 rounded-md border px-3 text-sm font-normal">{children}</select></label>}
