import Link from "next/link";
import { Eye, Filter, Plus } from "lucide-react";
import { AdminPageHeader } from "@/components/admin-page";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { CaseStatusBadge, ConfidentialityBadge } from "@/components/status-badges";
import { cases, formatDate } from "@/lib/demo-data";
export const metadata = { title: "Expedientes" };
export default function CasesPage() { return <><AdminPageHeader title="Expedientes judiciales" description="Radicación, asignación y seguimiento de los asuntos judiciales simulados." action={<Button asChild className="gap-2 bg-[#153b5c]"><Link href="/admin/expedientes/nuevo"><Plus className="size-4" /> Nuevo expediente</Link></Button>} /><div className="rounded-lg border bg-white"><div className="grid gap-3 border-b p-4 md:grid-cols-[1.5fr_repeat(3,1fr)_auto]"><Input placeholder="Buscar por radicado o parte…" /><FilterSelect placeholder="Sala" values={["Sala Penal", "Sala Civil", "Sala Laboral", "Sala Administrativa"]} /><FilterSelect placeholder="Estado" values={["Radicado", "En reparto", "Pruebas decretadas", "Audiencia programada"]} /><FilterSelect placeholder="Despacho" values={["Tribunal Superior", "Juzgado de Circuito"]} /><Button variant="outline" className="gap-2"><Filter className="size-4" /> Filtrar</Button></div><div className="overflow-x-auto"><Table><TableHeader><TableRow className="bg-slate-50"><TableHead>Radicado</TableHead><TableHead>Proceso / partes</TableHead><TableHead>Sala</TableHead><TableHead>Estado</TableHead><TableHead>Reserva</TableHead><TableHead>Radicación</TableHead><TableHead className="w-14" /></TableRow></TableHeader><TableBody>{cases.map((item) => <TableRow key={item.id}><TableCell><Link href={`/admin/expedientes/${item.id}`} className="mono-number text-xs font-semibold text-[#153b5c] hover:underline">{item.internalNumber}</Link><p className="mono-number mt-1 text-[10px] text-muted-foreground">{item.judicialNumber}</p></TableCell><TableCell className="max-w-[280px]"><p className="truncate text-sm font-medium text-[#153553]">{item.title}</p><p className="mt-1 truncate text-xs text-muted-foreground">{item.claimant} / {item.defendant}</p></TableCell><TableCell className="text-xs">{item.chamber}</TableCell><TableCell><CaseStatusBadge status={item.status} /></TableCell><TableCell><ConfidentialityBadge level={item.confidentiality} /></TableCell><TableCell className="text-xs">{formatDate(item.filedAt)}</TableCell><TableCell><Button asChild variant="ghost" size="icon"><Link href={`/admin/expedientes/${item.id}`} aria-label={`Ver ${item.internalNumber}`}><Eye className="size-4" /></Link></Button></TableCell></TableRow>)}</TableBody></Table></div><div className="flex items-center justify-between border-t p-4 text-xs text-muted-foreground"><span>Mostrando 1–4 de 1.248 expedientes</span><div className="flex gap-2"><Button variant="outline" size="sm" disabled>Anterior</Button><Button variant="outline" size="sm">Siguiente</Button></div></div></div></>; }
function FilterSelect({ placeholder, values }: { placeholder: string; values: string[] }) { return <Select><SelectTrigger className="w-full"><SelectValue placeholder={placeholder} /></SelectTrigger><SelectContent>{values.map((value) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select>; }
